config/routes.rb
Learnist::Application.routes.draw do
  
  devise_for :users
  get "things/new"
  get "things/create"
  root to: "static_pages#home"

  resources :users
  resources :things
  
  match '/signup', to: "users#new", :via =>[:get]
  get "users/show"

  match '/about', to: 'static_pages#about', :via =>[:get]
  match '/contact', to: 'static_pages#contact', :via =>[:get]

end

app/models/thing.rb
class Thing < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         #:confirmable

    has_many :things

	# Commented out to avoid duplication with devise
	#has_secure_password
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def new
  	@thing = Thing.new
  end

  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @thing = Thing.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

private
	
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Learnist</a>
    by OWL Laboratories
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
	<div class="container">
	  <%= link_to "Learnist", '#', id: "logo" %>
	  <nav>
		<ul class="nav pull-right">
			<% if user_signed_in? %>
				<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
				<li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
			<% else %>
				<li><%= link_to 'Sign Up', new_user_registration_path %></li>
				<li><%= link_to 'Sign In', new_user_session_path %></li>
			<% end %>
		  <li><%= link_to "Home", root_path %></li>
		  <li><%= link_to "About", about_path %></li>

		</ul>
	  </nav>
	</div>
  </div>
</header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Learnist</title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
	<%=render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	</div>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>What Learnist Does</h1>
<p> The keys to learning any new skill are daily repetition, and the motivation to keep going until you’re proficient. I see this with myself, and I see this with my students. The difference between a high school music teacher and concert violinist isn’t natural ability. It’s the drive to keep going hour after hour, day after day, until you hit the level that you’re looking for.
</p>

<p> At learn.io we’ve combined these two keys into one convenient and easy-to-use application. Just input what you want to learn, and then track the progress that you make towards each of these goals every time you log into the site. The goal is to make some progress every day, but I realize that life is busy, and things don’t necessarily happen every day. That’s what learn.io is here for. As you’re learning, it will keep track of what kind of progress you’re making towards different goals, and remind you if, for instance, you haven’t practiced guitar all week. 
</p>	

<p>
At the end of the week, learn.io will send you a customized email detailing what you’ve accomplished that week. This is where the second key comes in. A big part of keeping your motivation up when you’re learning something new and difficult is being able to feel proud of yourself when you see how far you’ve come. Like a mountain climber being able to look back at the ground below them, seeing that you’ve already made significant progress provides you with the push to keep going when you feel like you’re stuck in the woods. 
</p>

<p>
As a high school teacher, I see this all the time. My students who have the motivation and perseverance to keep at it hour after hour and day after day are the ones who make good marks. 
</p>

<p>
I think back to French class my first semester of college. At the end of the semester, I remember feeling frustrated that I’d been studying so hard all semester and I still couldn’t speak French. And my professor reminded us to think about where we were on the first day of class, when we couldn’t introduce ourselves, and compare that to where we were at the end of the semester. Not exactly speaking fluently, but at least able to string together a couple of broken sentences. 
</p>

<p>
That is what learn.io is here to do. 
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Learn Better</h1>

  <h2>
    Learning something new? Stay motivated with learnist. Its completely free. All it needs is five minutes of your time. 
  </h2>

  <%= link_to "Get Started!", new_user_registration_path , class: "btn btn-large btn-primary" %> 
  <%= link_to "More About Us", about_path , class: "btn btn-large btn-primary" %> 
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/things/create.html.erb
<h1>Things#create</h1>
<p>Find me in app/views/things/create.html.erb</p>

app/views/things/new.html.erb
<h1>Things#new</h1>
<p>Find me in app/views/things/new.html.erb</p>

app/views/users/new.html.erb
<title>New User</title>
<h1>Step 1. Sign Up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.text_field :password %>

		<%= f.label :password_confirmation %>
		<%= f.text_field :password_confirmation %>

		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<p>Welcome to your profile <%= @user.name %></p>
		<p>What are you learning?</p>
	</div>
	<div class="row">
	<div class="span6 offset3">
		<%= form_for(@thing) do |f| %>

		<%= f.label :title %>
		<%= f.text_field :title %>

		<%= f.submit "Add New Goal", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

</div>